# Generated by Django 6.0.5 on 2026-05-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='publicacoes/')),
                ('jornal', models.CharField(blank=True, max_length=100)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_aprovacao', 'Aguardando Aprovação do Cliente'), ('aprovado', 'Aprovado'), ('publicado', 'Publicado'), ('faturado', 'Faturado'), ('pago', 'Pago')], default='pendente', max_length=30)),
                ('valor_definido', models.BooleanField(default=False)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
    ]
