# Generated by Django 6.0.5 on 2026-05-13 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='arquivo_formatado',
            field=models.FileField(blank=True, null=True, upload_to='publicacoes/materias_formatadas/'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='publicacoes/textos_crus/'),
        ),
        migrations.CreateModel(
            name='MensagemPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='publicacoes.publicacao')),
            ],
            options={
                'verbose_name': 'Mensagem da Publicação',
                'verbose_name_plural': 'Mensagens da Publicação',
                'ordering': ['criada_em'],
            },
        ),
    ]
