# Generated by Django 6.0.5 on 2026-05-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0003_publicacao_arquivo_formatado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='tamanho',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
