# Generated by Django 6.0.5 on 2026-05-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0004_publicacao_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitação enviada'), ('pendente', 'Pendente'), ('aguardando_aprovacao', 'Aguardando Aprovação do Cliente'), ('aprovado', 'Aprovado'), ('publicado', 'Publicado'), ('faturado', 'Faturado'), ('pago', 'Pago')], default='pendente', max_length=30),
        ),
    ]
