# Generated by Django 6.0.5 on 2026-05-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0005_alter_publicacao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='valor_definido',
        ),
    ]
